(if (require 'subatomic-theme nil 'noerror)
    (setq prelude-theme 'subatomic-theme)
  (setq prelude-theme nil))
(tool-bar-mode -1)
(scroll-bar-mode -1)
(global-hl-line-mode -1)
(setq prelude-flyspell nil)
